import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import "./globals.css";

const plein = localFont({
  src: "../assets/fonts/Plein-Variable.woff2",
  variable: "--font-plein",
});

const switzer = localFont({
  src: "../assets/fonts/Switzer-Variable.woff2",
  variable: "--font-switzer",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${plein.variable} ${switzer.variable}`}>
      <body className="bg-background">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
